package com.czar.auth.config;

import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.ResourceLoader;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.security.KeyFactory;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;

/**
 * Loads the RSA key pair from PEM files on the classpath.
 * Local dev: keys/private.pem + keys/public.pem (gitignored, generated by scripts/generate-keys.sh)
 * Production: keys injected as env vars from GCP Secret Manager and written to classpath at startup.
 */
@Configuration
@EnableConfigurationProperties(JwtProperties.class)
public class RsaKeyConfig {

    private final JwtProperties props;
    private final ResourceLoader resourceLoader;

    public RsaKeyConfig(JwtProperties props, ResourceLoader resourceLoader) {
        this.props = props;
        this.resourceLoader = resourceLoader;
    }

    @Bean
    public RSAPrivateKey rsaPrivateKey() throws Exception {
        String pem = readPem(props.privateKeyPath());
        byte[] decoded = Base64.getDecoder().decode(pem);
        return (RSAPrivateKey) KeyFactory.getInstance("RSA")
                .generatePrivate(new PKCS8EncodedKeySpec(decoded));
    }

    @Bean
    public RSAPublicKey rsaPublicKey() throws Exception {
        String pem = readPem(props.publicKeyPath());
        byte[] decoded = Base64.getDecoder().decode(pem);
        return (RSAPublicKey) KeyFactory.getInstance("RSA")
                .generatePublic(new X509EncodedKeySpec(decoded));
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder(10);
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private String readPem(String location) throws Exception {
        var resource = resourceLoader.getResource(location);
        String raw = new String(resource.getInputStream().readAllBytes());
        // Strip PEM headers/footers and all whitespace so Base64.getDecoder() works
        return raw
                .replaceAll("-----BEGIN [^-]+-----", "")
                .replaceAll("-----END [^-]+-----", "")
                .replaceAll("\\s", "");
    }
}
